## UAS

In [31]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC

In [32]:
dataset = "https://raw.githubusercontent.com/Tegar11-F/Data-Set/main/Prediksi_BatuGinjal_Berdasarkan_Analisis_Urine.csv"
data = pd.read_csv(dataset)
data

gravity    ph  osmo  cond  urea   calc  target
0     1.021  4.91   725  14.0   443   2.45       0
1     1.017  5.74   577  20.0   296   4.49       0
2     1.008  7.20   321  14.9   101   2.36       0
3     1.011  5.51   408  12.6   224   2.15       0
4     1.005  6.52   187   7.5    91   1.16       0
..      ...   ...   ...   ...   ...    ...     ...
74    1.025  7.90   721  23.6   301   9.04       1
75    1.017  4.81   410  13.3   195   0.58       1
76    1.024  5.40   803  21.8   394   7.82       1
77    1.016  6.81   594  21.4   255  12.20       1
78    1.015  6.03   416  12.8   178   9.39       1

[79 rows x 7 columns]

Min Max Normalisasi

In [33]:
dataNormalisasi = ['gravity', 'ph', 'osmo','cond','urea','calc']
FrameNormalisasi = data[dataNormalisasi]
FrameNormalisasi

gravity    ph  osmo  cond  urea   calc
0     1.021  4.91   725  14.0   443   2.45
1     1.017  5.74   577  20.0   296   4.49
2     1.008  7.20   321  14.9   101   2.36
3     1.011  5.51   408  12.6   224   2.15
4     1.005  6.52   187   7.5    91   1.16
..      ...   ...   ...   ...   ...    ...
74    1.025  7.90   721  23.6   301   9.04
75    1.017  4.81   410  13.3   195   0.58
76    1.024  5.40   803  21.8   394   7.82
77    1.016  6.81   594  21.4   255  12.20
78    1.015  6.03   416  12.8   178   9.39

[79 rows x 6 columns]

In [34]:
scaler = MinMaxScaler()

In [35]:
# with open('ScalarMinMax','wb') as r:
#   pickle.dump(scaler,r)

In [36]:
scaler.fit(FrameNormalisasi)

MinMaxScaler()

In [37]:
hasilNormalisasi = scaler.transform(FrameNormalisasi)

In [38]:
hasilNormalisasi = pd.DataFrame(hasilNormalisasi,columns = dataNormalisasi)
hasilNormalisasi

gravity        ph      osmo      cond      urea      calc
0   0.457143  0.047170  0.512869  0.270517  0.709836  0.160903
1   0.342857  0.308176  0.371783  0.452888  0.468852  0.304869
2   0.085714  0.767296  0.127741  0.297872  0.149180  0.154552
3   0.171429  0.235849  0.210677  0.227964  0.350820  0.139732
4   0.000000  0.553459  0.000000  0.072948  0.132787  0.069866
..       ...       ...       ...       ...       ...       ...
74  0.571429  0.987421  0.509056  0.562310  0.477049  0.625970
75  0.342857  0.015723  0.212583  0.249240  0.303279  0.028934
76  0.542857  0.201258  0.587226  0.507599  0.629508  0.539873
77  0.314286  0.644654  0.387989  0.495441  0.401639  0.848977
78  0.285714  0.399371  0.218303  0.234043  0.275410  0.650670

[79 rows x 6 columns]

In [39]:
target = data[['target']]
label = pd.concat([target, hasilNormalisasi], axis=1)
label

target   gravity        ph      osmo      cond      urea      calc
0        0  0.457143  0.047170  0.512869  0.270517  0.709836  0.160903
1        0  0.342857  0.308176  0.371783  0.452888  0.468852  0.304869
2        0  0.085714  0.767296  0.127741  0.297872  0.149180  0.154552
3        0  0.171429  0.235849  0.210677  0.227964  0.350820  0.139732
4        0  0.000000  0.553459  0.000000  0.072948  0.132787  0.069866
..     ...       ...       ...       ...       ...       ...       ...
74       1  0.571429  0.987421  0.509056  0.562310  0.477049  0.625970
75       1  0.342857  0.015723  0.212583  0.249240  0.303279  0.028934
76       1  0.542857  0.201258  0.587226  0.507599  0.629508  0.539873
77       1  0.314286  0.644654  0.387989  0.495441  0.401639  0.848977
78       1  0.285714  0.399371  0.218303  0.234043  0.275410  0.650670

[79 rows x 7 columns]

In [40]:
percent_amount_of_test_data = 0.3

Menghitung Data
```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test
```

In [41]:
matrices_X = label.iloc[:,1:7].astype('int')
matrices_Y = label.iloc[:,0].astype('int')


In [42]:
X1 = label.iloc[:,1:7].values
Y1 = label.iloc[:, 0].values

In [43]:
X1

array([[0.45714286, 0.04716981, 0.5128694 , 0.27051672, 0.70983607,
        0.16090332],
       [0.34285714, 0.3081761 , 0.37178265, 0.45288754, 0.46885246,
        0.30486944],
       [0.08571429, 0.7672956 , 0.12774071, 0.29787234, 0.14918033,
        0.15455187],
       [0.17142857, 0.23584906, 0.21067684, 0.22796353, 0.35081967,
        0.13973183],
       [0.        , 0.55345912, 0.        , 0.07294833, 0.13278689,
        0.06986591],
       [0.42857143, 0.16037736, 0.45853194, 0.61398176, 0.39672131,
        0.22371207],
       [0.2       , 0.27044025, 0.26120114, 0.37386018, 0.30327869,
        0.08680311],
       [0.68571429, 0.28616352, 0.87702574, 0.93617021, 0.8852459 ,
        0.58645025],
       [0.28571429, 0.20440252, 0.33937083, 0.5106383 , 0.26229508,
        0.06986591],
       [0.45714286, 0.43081761, 0.564347  , 0.62613982, 0.60983607,
        0.14396613],
       [0.17142857, 0.44968553, 0.15061964, 0.19452888, 0.23278689,
        0.12420607],
       [0.57142857, 0

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [45]:
X_train.shape

(55, 6)

In [59]:
X1

array([[0.45714286, 0.04716981, 0.5128694 , 0.27051672, 0.70983607,
        0.16090332],
       [0.34285714, 0.3081761 , 0.37178265, 0.45288754, 0.46885246,
        0.30486944],
       [0.08571429, 0.7672956 , 0.12774071, 0.29787234, 0.14918033,
        0.15455187],
       [0.17142857, 0.23584906, 0.21067684, 0.22796353, 0.35081967,
        0.13973183],
       [0.        , 0.55345912, 0.        , 0.07294833, 0.13278689,
        0.06986591],
       [0.42857143, 0.16037736, 0.45853194, 0.61398176, 0.39672131,
        0.22371207],
       [0.2       , 0.27044025, 0.26120114, 0.37386018, 0.30327869,
        0.08680311],
       [0.68571429, 0.28616352, 0.87702574, 0.93617021, 0.8852459 ,
        0.58645025],
       [0.28571429, 0.20440252, 0.33937083, 0.5106383 , 0.26229508,
        0.06986591],
       [0.45714286, 0.43081761, 0.564347  , 0.62613982, 0.60983607,
        0.14396613],
       [0.17142857, 0.44968553, 0.15061964, 0.19452888, 0.23278689,
        0.12420607],
       [0.57142857, 0

In [46]:
Y1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

In [48]:
label

target   gravity        ph      osmo      cond      urea      calc
0        0  0.457143  0.047170  0.512869  0.270517  0.709836  0.160903
1        0  0.342857  0.308176  0.371783  0.452888  0.468852  0.304869
2        0  0.085714  0.767296  0.127741  0.297872  0.149180  0.154552
3        0  0.171429  0.235849  0.210677  0.227964  0.350820  0.139732
4        0  0.000000  0.553459  0.000000  0.072948  0.132787  0.069866
..     ...       ...       ...       ...       ...       ...       ...
74       1  0.571429  0.987421  0.509056  0.562310  0.477049  0.625970
75       1  0.342857  0.015723  0.212583  0.249240  0.303279  0.028934
76       1  0.542857  0.201258  0.587226  0.507599  0.629508  0.539873
77       1  0.314286  0.644654  0.387989  0.495441  0.401639  0.848977
78       1  0.285714  0.399371  0.218303  0.234043  0.275410  0.650670

[79 rows x 7 columns]

Naive Bayes

In [49]:
x = data.drop(columns='target') #Input
y = data['target'] #Output
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.30 , random_state=1)
model = GaussianNB()
model.fit(x_train , y_train)
pred = model.predict(x_test)
score = accuracy_score(y_test , pred)
print(score)

0.8333333333333334


Contoh terdapat data baru


---

*    gravity : 1.025
*    ph      : 7.90
*    osmo    : 721
*    cond    : 23.6
*    urea    : 301
*    calc    : 9.04

Mencari Target berdasarkan isi diatas

```
Target
[1.025,	7.90,	721,	23.6,	301,	9.04]
```



In [50]:
pred = model.predict(np.array([[1.025,	7.90,	721,	23.6,	301,	9.04]]))
pred

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"


array([1])

In [51]:
import pandas
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
import pickle
model = GaussianNB()
model.fit(X_train, y_train)
# save the model to disk
filename = 'model_batuginjal_NB.pkl'
pickle.dump(model, open(filename, 'wb'))

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


KNN

In [53]:
K = 15
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [54]:
Y_pred_knn = knn.predict(X_test)

In [55]:
knn.score(X_test, y_test)

0.375

In [56]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_knn)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for K - Nearest Neighbors\n',cm)
nn1_accuracy = round(100 * accuracy_score(y_test, Y_pred_knn), 2)
model_accuracy['1 - Nearest Neighbors'] = nn1_accuracy

nn1_precision = round(100 * precision_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_precision['1 - Nearest Neighbors'] = nn1_precision

nn1_recall = round(100 * recall_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_recall['1 - Nearest Neighbors'] = nn1_recall

print('The accuracy of this model is {} %.'.format(nn1_accuracy))
print('The precision of this model is {} %.'.format(nn1_precision))
print('The recall of this model is {} %.'.format(nn1_recall))

Confusion matrix for K - Nearest Neighbors
 [[ 8  4]
 [11  1]]
The accuracy of this model is 37.5 %.
The precision of this model is 31.05 %.
The recall of this model is 37.5 %.


desition tree

In [57]:
### Applying Decision Tree Classification model

decision_tree_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 15)
decision_tree_classifier.fit(X_train, y_train)


### Predicting the Test set results

Y_pred_dc = decision_tree_classifier.predict(X_test)

In [58]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Decision Tree\n',cm)

decision_tree_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Decision Tree'] = decision_tree_accuracy

decision_tree_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Decision Tree'] = decision_tree_precision

decision_tree_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Decision Tree'] = decision_tree_recall

print('The accuracy of this model is {} %.'.format(decision_tree_accuracy))
print('The precision of this model is {} %.'.format(decision_tree_precision))
print('The recall of this model is {} %.'.format(decision_tree_recall))

Confusion matrix for Decision Tree
 [[7 5]
 [7 5]]
The accuracy of this model is 50.0 %.
The precision of this model is 50.0 %.
The recall of this model is 50.0 %.
